- name: Remove existing job archiver app install
  file:
    path: : /usr/local/jobarchive
    state: absent

- name: job archiver directory
  file:
    path:: /usr/local/jobarchive
    state: directory

- git:
    repo: https://github.com/eesaanatluri/job_archive.git
    dest: /opt/job_archive
    clone: yes
    version: feat-uabrc-local-changes

- name: Run job arcive as the slurm user
  command: g++ job_archive.cpp -o job_archive -std=c++0x -lpthread
  become: true
  become_user: slurm

